In [1]:
#dependencies
import tweepy
import json
import numpy as np
import pandas as pd
from config import consumer_key, consumer_secret, access_token, access_token_secret

# Import and Initialize Sentiment Analyzer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

# Twitter API Keys
consumer_key = consumer_key
consumer_secret = consumer_secret
access_token = access_token
access_token_secret = access_token_secret

# Setup Tweepy API Authentication
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, parser=tweepy.parsers.JSONParser())

In [2]:
# Target Search Term
target_term = ["@BBC", "@CBS", "@CNN", "@nytimes", "@FoxNews"]

target_df = pd.DataFrame({"User": target_term})
target_df['Compound Score'] = ''
target_df['Positive Score'] = ''
target_df['Negative Score'] = ''
target_df['Neutral Score'] = ''

target_df

       User Compound Score Positive Score Negative Score Neutral Score
0      @BBC
1      @CBS
2      @CNN
3  @nytimes
4  @FoxNews

In [5]:
# Grab 100 tweets

sentiments = []

oldest_tweet = None

for target in target_term:
#     public_tweets = api.search(target, count=100, result_type="recent")
    public_tweets = api.user_timeline(target, max_id=oldest_tweet)
    
#     # Lists to hold sentiments
#     compound_sent = []
#     positive_sent = []
#     negative_sent = []
#     neutral_sent = []
    
    counter = 1
    
    # Loop through all tweets
    for tweet in public_tweets:

        # Run Vader Analysis on each tweet
        results = analyzer.polarity_scores(tweet['text'])
        compound = results["compound"]
        pos = results["pos"]
        neu = results["neu"]
        neg = results["neg"]
        tweets_ago = counter
        
        oldest_tweet = tweet['id'] - 1
        
        sentiments.append({"Date": tweet['created_at'],
                          "Compound": compound,
                          "Positive": pos,
                          "Negative": neg,
                          "Neutral": neu,
                          "Tweets Ago": counter})
        
        counter += 1
    
#     complist.append(np.mean(compound_sent))
#     poslist.append(np.mean(positive_sent))
#     neglist.append(np.mean(negative_sent))
#     neulist.append(np.mean(neutral_sent))

# target_df['Compound Score'] = complist
# target_df['Positive Score'] = poslist
# target_df['Negative Score'] = neglist
# target_df['Neutral Score'] = neulist

# print("VADER Sentiment Analysis for 100 Most Recent Tweets")
# target_df

In [7]:
sentiments_pd = pd.DataFrame.from_dict(sentiments)
sentiments_pd

,Compound,Date,Negative,Neutral,Positive,Tweets Ago
0,-0.5106,Wed Jun 27 11:52:00 +0000 2018,0.350,0.650,0.000,1
1,0.9403,Wed Jun 27 11:39:52 +0000 2018,0.000,0.536,0.464,2
2,0.0000,Wed Jun 27 11:03:04 +0000 2018,0.000,1.000,0.000,3
3,0.0000,Wed Jun 27 09:30:20 +0000 2018,0.000,1.000,0.000,4
4,0.6114,Wed Jun 27 08:47:40 +0000 2018,0.050,0.756,0.194,5
5,0.0000,Wed Jun 27 08:01:05 +0000 2018,0.000,1.000,0.000,6
6,0.5106,Wed Jun 27 07:29:04 +0000 2018,0.047,0.809,0.145,7
7,0.4939,Wed Jun 27 07:01:05 +0000 2018,0.000,0.856,0.144,8
8,0.0000,Tue Jun 26 21:20:15 +0000 2018,0.000,1.000,0.000,9
9,0.0000,Tue Jun 26 19:05:08 +0000 2018,0.000,1.000,0.000,10
10,0.2960,Tue Jun 26 18:03:06 +0000 2018,0.074,0.792,0.134,11
11,0.0000,Tue Jun 26 17:02:02 +0000 2018,0.000,1.000,0.000,12
12,0.0000,Tue Jun 26 16:33:41 +0000 2018,0.000,1.000,0.000,13
13,0.0000,Tue Jun 26 16:00:15 +0000 2018,0.000,1.000,0.000,14
14,0.0000,Tue Jun 26 14:52:03 +0000 2018,0.000,1.000,0.000,15
15,0.8360,Tue Jun 26 14:32:33 +0000 2018,0.000,0.683,0.317,16
16,0.6114,Tue Jun 26 13:12:16 +0000 2018,0.000,0.818,0.182,17
17,0.0000,Tue Jun 26 12:58:04 +0000 2018,0.000,1.000,0.000,18
18,0.5267,Tue Jun 26 12:02:04 +0000 2018,0.000,0.673,0.327,19
19,0.0000,Tue Jun 26 11:02:03 +0000 2018,0.000,1.000,0.000,20
20,0.5574,Mon Jun 25 18:20:25 +0000 2018,0.000,0.796,0.204,1
21,0.1867,Fri Jun 22 21:19:06 +0000 2018,0.000,0.902,0.098,2
22,0.4199,Fri Jun 22 18:33:53 +0000 2018,0.000,0.811,0.189,3
23,0.4926,Thu Jun 21 23:29:50 +0000 2018,0.000,0.803,0.197,4
24,0.3555,Wed Jun 20 00:39:01 +0000 2018,0.122,0.680,0.199,5
25,0.0000,Mon Jun 18 20:27:50 +0000 2018,0.000,1.000,0.000,6
26,0.0000,Mon Jun 18 15:00:46 +0000 2018,0.000,1.000,0.000,7
27,0.9392,Sun Jun 17 13:00:01 +0000 2018,0.000,0.507,0.493,8
28,0.3595,Fri Jun 15 18:48:29 +0000 2018,0.000,0.872,0.128,9
29,-0.2960,Thu Jun 14 17:30:00 +0000 2018,0.167,0.833,0.000,10
...,...,...,...,...,...,...
50,0.0000,Sun Jun 10 22:40:04 +0000 2018,0.000,1.000,0.000,11
51,0.4588,Sun Jun 10 22:30:04 +0000 2018,0.083,0.694,0.222,12
52,-0.2732,Sun Jun 10 22:20:07 +0000 2018,0.110,0.890,0.000,13
53,0.3612,Sun Jun 10 22:20:00 +0000 2018,0.000,0.878,0.122,14
54,0.0000,Sun Jun 10 22:10:05 +0000 2018,0.000,1.000,0.000,15
55,-0.2500,Sun Jun 10 22:00:09 +0000 2018,0.080,0.920,0.000,16
56,0.0000,Sun Jun 10 21:50:00 +0000 2018,0.000,1.000,0.000,17
57,-0.3818,Sun Jun 10 21:40:05 +0000 2018,0.206,0.794,0.000,18
58,0.0000,Sun Jun 10 21:30:00 +0000 2018,0.000,1.000,0.000,19
59,-0.4404,Sun Jun 10 21:20:10 +0000 2018,0.197,0.687,0.116,20
60,-0.1779,Sun Jun 10 21:15:08 +0000 2018,0.082,0.918,0.000,1
61,0.0000,Sun Jun 10 21:00:03 +0000 2018,0.000,1.000,0.000,2
62,-0.6395,Sun Jun 10 20:45:08 +0000 2018,0.209,0.791,0.000,3
63,0.0258,Sun Jun 10 20:30:04 +0000 2018,0.000,0.956,0.044,4
64,0.6908,Sun Jun 10 20:15:05 +0000 2018,0.000,0.749,0.251,5
65,-0.1526,Sun Jun 10 20:00:11 +0000 2018,0.140,0.748,0.112,6
66,0.7906,Sun Jun 10 19:45:05 +0000 2018,0.000,0.682,0.318,7
67,0.0000,Sun Jun 10 19:33:38 +0000 2018,0.000,1.000,0.000,8
68,-0.7269,Sun Jun 10 19:30:02 +0000 2018,0.254,0.660,0.086,9
69,0.2732,Sun Jun 10 19:15:07 +0000 2018,0.000,0.905,0.095,10
70,0.5423,Sun Jun 10 19:00:06 +0000 2018,0.000,0.811,0.189,11
71,0.0000,Sun Jun 10 18:45:07 +0000 2018,0.000,1.000,0.000,12
72,0.0000,Sun Jun 10 18:30:05 +0000 2018,0.000,1.000,0.000,13
73,0.0000,Sun Jun 10 18:15:04 +0000 2018,0.000,1.000,0.000,14
74,0.5267,Sun Jun 10 18:00:02 +0000 2018,0.082,0.672,0.246,15
75,-0.2960,Sun Jun 10 17:45:05 +0000 2018,0.109,0.891,0.000,16
76,-0.8481,Sun Jun 10 17:30:07 +0000 2018,0.353,0.647,0.000,17
77,0.0000,Sun Jun 10 17:15:08 +0000 2018,0.000,1.000,0.000,18
78,-0.1779,Sun Jun 10 17:00:05 +0000 2018,0.078,0.922,0.000,19
79,0.0000,Sun Jun 10 16:45:04 +0000 2018,0.000,1.000,0.000,20